import tempfile
import unittest
from pathlib import Path

from openpyxl import Workbook, load_workbook

from invoice_system.excel_store import InvoiceWorkbook, load_invoice_records
from invoice_system.models import EXCEL_HEADERS, InvoiceRecord, OCRAuditRow, SourceQARecord


class ExcelStoreTests(unittest.TestCase):
    def test_writes_13_headers(self):
        with tempfile.TemporaryDirectory() as temp:
            out = Path(temp) / "Invoice_Output.xlsx"
            store = InvoiceWorkbook(out)
            store.write_records([InvoiceRecord(invoice_date="2026-06-12", seller="Cafe", total_amount=10)])
            wb = load_workbook(out)
            headers = [cell.value for cell in wb.active[1]]
            self.assertEqual(headers, EXCEL_HEADERS)
            wb.close()

    def test_load_invoice_records_uses_invoices_sheet_even_when_not_active(self):
        with tempfile.TemporaryDirectory() as temp:
            path = Path(temp) / "ubuntu_output.xlsx"
            wb = Workbook()
            summary = wb.active
            summary.title = "Summary"
            summary.append(["Metric", "Value"])
            ws = wb.create_sheet("Invoices")
            ws.append(EXCEL_HEADERS)
            record = InvoiceRecord(invoice_date="2026-06-12", seller="Cafe", total_amount=10)
            record.line_no = 1
            ws.append(record.to_excel_row())
            wb.save(path)
            wb.close()

            rows = load_invoice_records(path)

            self.assertEqual(len(rows), 1)
            self.assertEqual(rows[0].seller, "Cafe")

    def test_load_invoice_records_finds_header_sheet_without_invoices_name(self):
        with tempfile.TemporaryDirectory() as temp:
            path = Path(temp) / "ubuntu_output.xlsx"
            wb = Workbook()
            summary = wb.active
            summary.title = "Run_Summary"
            summary.append(["Metric", "Value"])
            ws = wb.create_sheet("Sheet1")
            ws.append(EXCEL_HEADERS)
            record = InvoiceRecord(invoice_date="2026-06-12", seller="Cafe", total_amount=10)
            record.line_no = 1
            ws.append(record.to_excel_row())
            wb.save(path)
            wb.close()

            rows = load_invoice_records(path)

            self.assertEqual(len(rows), 1)
            self.assertEqual(rows[0].seller, "Cafe")

    def test_load_invoice_records_skips_blank_and_note_rows(self):
        with tempfile.TemporaryDirectory() as temp:
            path = Path(temp) / "ubuntu_output.xlsx"
            wb = Workbook()
            ws = wb.active
            ws.title = "Invoices"
            ws.append(EXCEL_HEADERS)
            record = InvoiceRecord(invoice_date="2026-06-12", seller="Cafe", total_amount=10)
            record.line_no = 1
            ws.append(record.to_excel_row())
            ws.append([None] * len(EXCEL_HEADERS))
            ws.append(["Generated by Ubuntu script", None, None])
            wb.save(path)
            wb.close()

            rows = load_invoice_records(path)

            self.assertEqual(len(rows), 1)
            self.assertEqual(rows[0].seller, "Cafe")

    def test_generates_manual_checked_workbook_for_human_review(self):
        with tempfile.TemporaryDirectory() as temp:
            temp_path = Path(temp)
            out = temp_path / "Invoice_Output.xlsx"
            manual = temp_path / "Invoice_Manually_Checked.xlsx"
            store = InvoiceWorkbook(out, manual)

            store.write_records([InvoiceRecord(invoice_date="2026-06-12", seller="Cafe", total_amount=10)])

            self.assertTrue(out.exists())
            self.assertTrue(manual.exists())
            wb = load_workbook(manual, data_only=True)
            self.assertEqual([cell.value for cell in wb.active[1]], EXCEL_HEADERS)
            self.assertEqual(wb.active.cell(2, 11).value, "Cafe")
            wb.close()

    def test_preserves_locked_manual_checked_row(self):
        with tempfile.TemporaryDirectory() as temp:
            temp_path = Path(temp)
            manual = temp_path / "Invoice_Manually_Checked.xlsx"
            locked = InvoiceRecord(invoice_date="2026-06-12", seller="Cafe", total_amount=10, status="Manually checked")
            _write_manual_records(manual, [locked])

            out = temp_path / "Invoice_Output.xlsx"
            store = InvoiceWorkbook(out, manual)
            written = store.write_records([InvoiceRecord(invoice_date="2026-06-12", seller="Cafe", total_amount=10)])
            self.assertEqual(written, 0)
            saved_wb = load_workbook(out)
            saved = saved_wb.active
            self.assertEqual(saved.max_row, 2)
            self.assertEqual(saved.cell(2, 13).value, "Manually checked")
            saved_wb.close()

    def test_preserves_locked_deleted_row(self):
        with tempfile.TemporaryDirectory() as temp:
            temp_path = Path(temp)
            manual = temp_path / "Invoice_Manually_Checked.xlsx"
            locked = InvoiceRecord(invoice_date="2026-06-12", seller="Cafe", total_amount=10, status="Deleted")
            _write_manual_records(manual, [locked])

            out = temp_path / "Invoice_Output.xlsx"
            store = InvoiceWorkbook(out, manual)
            written = store.write_records([InvoiceRecord(invoice_date="2026-06-12", seller="Cafe", total_amount=10)])

            self.assertEqual(written, 0)
            saved_wb = load_workbook(out)
            saved = saved_wb.active
            self.assertEqual(saved.max_row, 2)
            self.assertEqual(saved.cell(2, 13).value, "Deleted")
            saved_wb.close()

    def test_locked_status_matching_ignores_case_and_whitespace(self):
        with tempfile.TemporaryDirectory() as temp:
            temp_path = Path(temp)
            manual = temp_path / "Invoice_Manually_Checked.xlsx"
            locked = InvoiceRecord(invoice_date="2026-06-12", seller="Cafe", total_amount=10, status=" manually CHECKED ")
            _write_manual_records(manual, [locked])

            out = temp_path / "Invoice_Output.xlsx"
            store = InvoiceWorkbook(out, manual)
            written = store.write_records([InvoiceRecord(invoice_date="2026-06-12", seller="Cafe", total_amount=10)])

            self.assertEqual(written, 0)
            saved_wb = load_workbook(out)
            self.assertEqual(saved_wb.active.cell(2, 13).value, " manually CHECKED ")
            saved_wb.close()

    def test_locked_row_matching_normalizes_date_and_seller(self):
        with tempfile.TemporaryDirectory() as temp:
            temp_path = Path(temp)
            manual = temp_path / "Invoice_Manually_Checked.xlsx"
            seller = "Caf" + chr(0xE9) + " Xu" + chr(0xE1) + "n"
            locked = InvoiceRecord(invoice_date="12/06/2026", seller=seller, total_amount=10, status="Manually checked")
            _write_manual_records(manual, [locked])

            out = temp_path / "Invoice_Output.xlsx"
            store = InvoiceWorkbook(out, manual)
            written = store.write_records([InvoiceRecord(invoice_date="2026-06-12", seller="Cafe Xuan", total_amount=10)])

            self.assertEqual(written, 0)
            saved_wb = load_workbook(out)
            saved = saved_wb.active
            self.assertEqual(saved.max_row, 2)
            self.assertEqual(saved.cell(2, 2).value, "12/06/2026")
            self.assertEqual(saved.cell(2, 11).value, seller)
            self.assertEqual(saved.cell(2, 13).value, "Manually checked")
            saved_wb.close()

    def test_locked_records_use_invoices_sheet_even_when_manual_active_sheet_is_summary(self):
        with tempfile.TemporaryDirectory() as temp:
            temp_path = Path(temp)
            manual = temp_path / "Invoice_Manually_Checked.xlsx"
            wb = Workbook()
            summary = wb.active
            summary.title = "Summary"
            summary.append(["Metric", "Value"])
            ws = wb.create_sheet("Invoices")
            ws.append(EXCEL_HEADERS)
            locked = InvoiceRecord(invoice_date="2026-06-12", seller="Cafe", total_amount=10, status="Manually checked")
            locked.line_no = 1
            ws.append(locked.to_excel_row())
            ws.append([None] * len(EXCEL_HEADERS))
            ws.append(["Operator note", None, None])
            wb.save(manual)
            wb.close()

            out = temp_path / "Invoice_Output.xlsx"
            store = InvoiceWorkbook(out, manual)
            written = store.write_records([InvoiceRecord(invoice_date="2026-06-12", seller="Cafe", total_amount=10)])

            self.assertEqual(written, 0)
            saved_wb = load_workbook(out, data_only=True)
            self.assertEqual(saved_wb["Invoices"].max_row, 2)
            self.assertEqual(saved_wb["Invoices"].cell(2, 13).value, "Manually checked")
            saved_wb.close()

    def test_writes_ocr_audit_sheet(self):
        with tempfile.TemporaryDirectory() as temp:
            out = Path(temp) / "Invoice_Output.xlsx"
            store = InvoiceWorkbook(out)
            store.write_records(
                [InvoiceRecord(invoice_date="2026-06-12", seller="Cafe", total_amount=10)],
                [
                    OCRAuditRow(
                        source_image="source.jpg",
                        crop_image="crop.jpg",
                        decision="local OCR agreement",
                        used_codex=False,
                        paddle_confidence=0.9,
                        easy_confidence=0.8,
                        paddle_text="Cafe",
                        easy_text="Cafe",
                    )
                ],
            )
            wb = load_workbook(out, data_only=True)
            self.assertIn("OCR_Audit", wb.sheetnames)
            ws = wb["OCR_Audit"]
            self.assertEqual(ws.cell(2, 3).value, "local OCR agreement")
            self.assertEqual(ws.cell(2, 4).value, "no")
            wb.close()

    def test_writes_run_summary_sheet(self):
        with tempfile.TemporaryDirectory() as temp:
            out = Path(temp) / "Invoice_Output.xlsx"
            store = InvoiceWorkbook(out)
            store.write_records(
                [InvoiceRecord(invoice_date="2026-06-12", seller="Cafe", total_amount=10)],
                [
                    OCRAuditRow("source.jpg", "crop1.jpg", "local OCR agreement", False),
                    OCRAuditRow("source.jpg", "crop2.jpg", "missing key fields; noise filtered", False),
                    OCRAuditRow("source2.jpg", "crop3.jpg", "OCR mismatch", True),
                ],
            )
            wb = load_workbook(out, data_only=True)
            self.assertEqual(wb.sheetnames[:3], ["Invoices", "Run_Summary", "OCR_Audit"])
            summary = {row[0]: row[1] for row in wb["Run_Summary"].iter_rows(values_only=True) if row[0]}
            self.assertEqual(summary["Source images"], 2)
            self.assertEqual(summary["Crops processed"], 3)
            self.assertEqual(summary["Invoice rows"], 1)
            self.assertEqual(summary["Noise filtered crops"], 1)
            self.assertEqual(summary["Codex Scan attempted"], 1)
            self.assertEqual(summary["Codex Scan used"], 1)
            wb.close()

    def test_writes_source_qa_sheet(self):
        with tempfile.TemporaryDirectory() as temp:
            out = Path(temp) / "Invoice_Output.xlsx"
            store = InvoiceWorkbook(out)
            store.write_records(
                [InvoiceRecord(invoice_date="2026-06-12", seller="Cafe", total_amount=10)],
                [OCRAuditRow("source.jpg", "crop1.jpg", "local OCR agreement", False)],
                [
                    SourceQARecord(
                        source_image="source.jpg",
                        ai_visual_count=9,
                        opencv_crop_count=6,
                        final_invoice_rows=5,
                        needs_human_review=True,
                        reason="AI count 9 != OpenCV crops 6",
                        ai_confidence=0.9,
                    )
                ],
            )

            wb = load_workbook(out, data_only=True)
            self.assertIn("Source_QA", wb.sheetnames)
            ws = wb["Source_QA"]
            self.assertEqual(ws.cell(2, 2).value, 9)
            self.assertEqual(ws.cell(2, 3).value, 6)
            self.assertEqual(ws.cell(2, 5).value, "yes")
            wb.close()

    def test_run_summary_counts_codex_attempt_when_unavailable(self):
        with tempfile.TemporaryDirectory() as temp:
            out = Path(temp) / "Invoice_Output.xlsx"
            store = InvoiceWorkbook(out)
            store.write_records(
                [InvoiceRecord(invoice_date="2026-06-12", seller="Cafe", total_amount=10)],
                [
                    OCRAuditRow(
                        "source.jpg",
                        "crop1.jpg",
                        "OCR mismatch",
                        False,
                        codex_error="OPENAI_API_KEY is not configured",
                    )
                ],
            )

            wb = load_workbook(out, data_only=True)
            summary = {row[0]: row[1] for row in wb["Run_Summary"].iter_rows(values_only=True) if row[0]}
            self.assertEqual(summary["Codex Scan attempted"], 1)
            self.assertEqual(summary["Codex Scan used"], 0)
            wb.close()

    def test_run_summary_does_not_double_count_locked_duplicate_input(self):
        with tempfile.TemporaryDirectory() as temp:
            temp_path = Path(temp)
            manual = temp_path / "Invoice_Manually_Checked.xlsx"
            locked = InvoiceRecord(invoice_date="2026-06-12", seller="Cafe", total_amount=10, status="Manually checked")
            _write_manual_records(manual, [locked])

            out = temp_path / "Invoice_Output.xlsx"
            store = InvoiceWorkbook(out, manual)
            written = store.write_records(
                [
                    InvoiceRecord(invoice_date="2026-06-12", seller="Cafe", total_amount=10),
                    InvoiceRecord(invoice_date="2026-06-13", seller="Market", total_amount=20),
                ],
                [
                    OCRAuditRow("source.jpg", "crop1.jpg", "local OCR agreement", False),
                    OCRAuditRow("source.jpg", "crop2.jpg", "local OCR agreement", False),
                ],
            )

            self.assertEqual(written, 1)
            wb = load_workbook(out, data_only=True)
            summary = {row[0]: row[1] for row in wb["Run_Summary"].iter_rows(values_only=True) if row[0]}
            self.assertEqual(summary["Invoice rows"], 2)
            self.assertEqual(summary["New rows written"], 1)
            self.assertEqual(summary["Locked rows preserved"], 1)
            self.assertEqual(wb["Invoices"].max_row, 3)
            wb.close()

    def test_manual_checked_workbook_sync_preserves_locked_and_adds_new_rows(self):
        with tempfile.TemporaryDirectory() as temp:
            temp_path = Path(temp)
            manual = temp_path / "Invoice_Manually_Checked.xlsx"
            locked = InvoiceRecord(invoice_date="2026-06-12", seller="Cafe", total_amount=10, status="Manually checked")
            _write_manual_records(manual, [locked])

            out = temp_path / "Invoice_Output.xlsx"
            store = InvoiceWorkbook(out, manual)
            store.write_records(
                [
                    InvoiceRecord(invoice_date="2026-06-12", seller="Cafe", total_amount=10),
                    InvoiceRecord(invoice_date="2026-06-13", seller="Market", total_amount=20),
                ]
            )

            wb = load_workbook(manual, data_only=True)
            ws = wb.active
            self.assertEqual(ws.max_row, 3)
            self.assertEqual(ws.cell(2, 13).value, "Manually checked")
            self.assertEqual(ws.cell(3, 11).value, "Market")
            wb.close()


def _write_manual_records(path: Path, records: list[InvoiceRecord]) -> None:
    wb = Workbook()
    ws = wb.active
    ws.append(EXCEL_HEADERS)
    for index, record in enumerate(records, start=1):
        record.line_no = index
        ws.append(record.to_excel_row())
    wb.save(path)
    wb.close()


if __name__ == "__main__":
    unittest.main()
